# Generated by Django 6.0.7 on 2026-07-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=1, help_text='Enter a value between 0 and 100.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
