# Generated by Django 6.0.7 on 2026-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_education_delete_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('display_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['date', 'display_order'],
            },
        ),
    ]
