# Generated by Django 6.0.7 on 2026-07-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed About Me section.'),
        ),
    ]
